### ISSUE TITLE
SignInManager registration error

### ISSUE THREAD

**Issue by bozau** [cskardon/Neo4j.AspNet.Identity.Core#2]
Created new project (.Net Core 1.1, Web App, Individual Accounts) followed instructions (using NuGet Package Neo4j.AspNet.Identity.Core (0.1.0-alpha)

Upon starting up the application (IIS or Project) I receive;

```
InvalidOperationException: No service for type 'Microsoft.AspNetCore.Identity.SignInManager`1[WebApplication2.Models.ApplicationUser]' has been registered.

Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
```
At;
```
AspNetCore._Views_Shared__Layout_cshtml+<ExecuteAsync>d__64.MoveNext() in _Layout.cshtml
                    @await Html.PartialAsync("_LoginPartial")
```

**Comment by cskardon** [comment]
Can you try changing the `ApplicationUser` you have to be:

`public class ApplicationUser : Neo4j.AspNet.Identity.Core.IdentityUser`

(It'll be in the `Models` folder...)
I think it might be that - if it is, I'll update the ReadMe....

**Comment by bozau** [comment]
Sadly that hasn't fixed it, same message, I've published the project I'm testing with for you: https://github.com/aboeren/Neo4j.AspNet.Identity.Core.NuGetTest

Is it possible that a custom SignInManager might need to be required?

**Comment by cskardon** [comment]
Got it,

So, in the `Startup.cs` file you have the following line (in the `ConfigureServices` method):

`services.AddIdentity<Neo4j.AspNet.Identity.Core.ApplicationUser, Neo4jIdentityRole>()`

If you change this to:

`services.AddIdentity<Model.ApplicationUser, Neo4jIdentityRole>()`

you'll use the `ApplicationUser` in your codebase, _if_ you want to use the `ApplicationUser` within the Neo4j package, you'll need to delete the `ApplicationUser.cs` file in the `Models` folder, and then hunt out the uses of it (so things like `_LoginPartial.cshtml`) - easiest is to delete the file and then do a build to find out the places it's used :o

**Comment by bozau** [comment]
Ok, changing the AddIdentity line seems to allow it to start :) (No longer getting the message)

Will just add an OAuth provided and test it out 👍
